require:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.0

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 80

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  AllowedMethods:
    - split_into_words

Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"
    - "**/*.gemspec"

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  AllowedMethods:
    - split_into_words

Metrics/MethodLength:
  AllowedMethods:
    - split_into_words

Metrics/PerceivedComplexity:
  Max: 5
  AllowedMethods:
    - split_into_words

Naming/FileName:
  Exclude:
    - "lib/strings-case.rb"

Style/BlockDelimiters:
  AllowedMethods:
    - expect
    - let

Style/CommentedKeyword:
  Enabled: false

Style/FetchEnvVar:
  AllowedVars:
    - COVERAGE

Style/FormatString:
  EnforcedStyle: percent

Style/NegatedWhile:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
