AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  CountComments: true
  Max: 32
  IgnoredMethods: []
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 1500

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Naming/BinaryOperatorParameterName:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Style/FormatString:
  EnforcedStyle: percent

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Enabled: false

# { ... } for multi-line blocks is okay
Style/BlockDelimiters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false
